---
- name: Deploy to Kubernetes
  hosts: dockerhost  
  vars:
    image_name: "johnberb/myapp"
    image_tag: "latest"
    k8s_namespace: "default"

  tasks:
    - name: Deploy to Kubernetes
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: "myapp"
            namespace: "{{ k8s_namespace }}"
          spec:
            replicas: 3
            selector:
              matchLabels:
                app: "myapp"
            template:
              metadata:
                labels:
                  app: "myapp"
              spec:
                containers:
                - name: "myapp"
                  image: "{{ image_name }}:{{ image_tag }}"
                  ports:
                  - containerPort: 8080
    - name: Expose NodePort Service
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Service
          metadata:
            name: "myapp"
            namespace: "{{ k8s_namespace }}"
          spec:
            type: NodePort
            selector:
              app: "myapp"
            ports:
              - port: 8080
                targetPort: 8080